# This is a basic workflow to help you get started with Actions

name: Build Android TV
defaults:
  run:
    shell: bash
    
on:
  # schedule:
  #   - cron: "0 0 * * 0"  # Runs once a week (Sunday at midnight)
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:        
      - name: Make directories
        run: |
          mkdir -p $HOME/DivestOS-Build/Build/LineageOS-21.0
       
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y autoconf automake bc bison build-essential ccache curl flex g++ gawk git-core git-lfs gnupg gperf lib32ncurses5-dev lib32z1-dev libgmp-dev libmpc-dev libmpfr-dev libncurses5-dev python3 python3-pip python3-venv zip zlib1g-dev

      - name: Install repo
        run: |
          mkdir -p ~/.bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          chmod a+rx ~/.bin/repo
          echo ~/.bin >> $GITHUB_PATH
          
      - name: Configure Git
        run: |
          umask 0022
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git lfs install
          git submodule update --init --recursive
          
      - name: Setup caching
        run: |
          mkdir -p ccache
          echo "export USE_CCACHE=1;" >> $GITHUB_PATH
          echo "export CCACHE_COMPRESS=1;" >> $GITHUB_PATH
          echo "export CCACHE_COMPRESSLEVEL=1;" >> $GITHUB_PATH
          echo "export CCACHE_EXEC=/usr/bin/ccache;" >> $GITHUB_PATH
          echo "export CCACHE_DIR=[PATH TO CCACHE DIRECTORY];" >> $GITHUB_PATH
          ccache -M 128GB
          
      # - name: Checkout repository
      #   uses: actions/checkout@v4
        
      # - name: Copy files
      #   run: cp -r "$GITHUB_WORKSPACE/" $HOME/
      
      - name: Download source code
        run: |
          cd $HOME/DivestOS-Build/Build/LineageOS-21.0
          repo init -u https://github.com/LineageOS/android.git -b lineage-21.0 --git-lfs --repo-url=https://gerrit.googlesource.com/git-repo --repo-rev=stable
          repo sync --force-sync

      - name: Start build
        run: |
          cd $HOME/DivestOS-Build/Build/LineageOS-21.0;
          # source $HOME/DivestOS-Build/Scripts/init.sh;
          source $HOME/DivestOS-Build/Build/LineageOS-21.0/build/envsetup.sh;
          # resetWorkspace;
          # Remove remenants
          rm -rf packages/apps/Fennec_DOS-Shim/ vendor/divested/ vendor/fdroid_prebuilt/ packages/apps/SupportDivestOS/ packages/apps/OpenEUICC/
          rm -rf out;
          #patchWorkspace;
          breakfast virtio_x86_64_tv
          m isoimage-install
        shell: bash
          
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: nightly-tag-${{ env.NOW }}
          name: nightly-release-${{ env.NOW }}
          body: DivestOS build for x84_64 Android TV
          artifacts: |
            $DOS_BUILDS/*.zip
